// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvnfincgywggpvctgbhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bmZpbmNneXdnZ3B2Y3RnYmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDY0NjQsImV4cCI6MjA1OTkyMjQ2NH0.RHRNxgkGrg79aOew-ObjecgUp6FnrthnAegwjFjROhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);